const books = [
  {
    _id: 1,
    title: "উড়ালপঙ্খী",
    author: "তৌহিদ হাসান",
    genre: {
      name: "উপন্যাস",
      _id: 1,
    },
    price: "৫৬৭",
    pageNumber: "২৯৬",
    publishedYear: "২০২১",
    image: "/images/uralponkhi.jpg",
    buyLink: "https://www.rokomari.com/book/212961/uralpongkhi",
  },
  {
    _id: 1,
    title: "সাদা পালকের নির্জনতা",
    author: "মাহরীন ফেরদৌস",
    genre: {
      name: "উপন্যাস",
      _id: 1,
    },
    price: "৪৮০",
    pageNumber: "২৯৬",
    publishedYear: "২০২১",
    image: "/images/sada paloker nirjonota.jpg",
    buyLink: "https://www.rokomari.com/book/207463/sada-paloker-nirjonota",
  },
  {
    _id: 3,
    title: "সাদা পালকের নির্জনতা",
    author: "মাহরীন ফেরদৌস",
    genre: {
      name: "উপন্যাস",
      _id: 1,
    },
    price: "৪৮০",
    pageNumber: "২৯৬",
    publishedYear: "২০২১",
    image: "/images/sada paloker nirjonota.jpg",
    buyLink: "https://www.rokomari.com/book/207463/sada-paloker-nirjonota",
  },
  {
    _id: 4,
    title: "সাদা পালকের নির্জনতা",
    author: "মাহরীন ফেরদৌস",
    genre: {
      name: "উপন্যাস",
      _id: 1,
    },
    price: "৪৮০",
    pageNumber: "২৯৬",
    publishedYear: "২০২১",
    image: "/images/sada paloker nirjonota.jpg",
    buyLink: "https://www.rokomari.com/book/207463/sada-paloker-nirjonota",
  },
  {
    _id: 8,
    title: "উড়ালপঙ্খী",
    author: "তৌহিদ হাসান",
    genre: {
      name: "উপন্যাস",
      _id: 1,
    },
    price: "৫৬৭",
    pageNumber: "২৯৬",
    publishedYear: "২০২১",
    image: "/images/uralponkhi.jpg",
    buyLink: "https://www.rokomari.com/book/212961/uralpongkhi",
  },
  {
    _id: 5,
    title: "সাদা পালকের নির্জনতা",
    author: "মাহরীন ফেরদৌস",
    genre: {
      name: "গল্প",
      _id: 2,
    },
    price: "৪৮০",
    pageNumber: "২৯৬",
    publishedYear: "২০১৯",
    image: "/images/sada paloker nirjonota.jpg",
    buyLink: "https://www.rokomari.com/book/207463/sada-paloker-nirjonota",
  },
  {
    _id: 6,
    title: "সাদা পালকের নির্জনতা",
    author: "মাহরীন ফেরদৌস",
    genre: {
      name: "গল্প",
      _id: 2,
    },
    price: "৪৮০",
    pageNumber: "২৯৬",
    publishedYear: "২০২২",
    image: "/images/sada paloker nirjonota.jpg",
    buyLink: "https://www.rokomari.com/book/207463/sada-paloker-nirjonota",
  },
  {
    _id: 7,
    title: "সাদা পালকের নির্জনতা",
    author: "মাহরীন ফেরদৌস",
    genre: {
      name: "গল্প",
      _id: 2,
    },
    price: "৪৮০",
    pageNumber: "২৯৬",
    publishedYear: "২০২০",
    image: "/images/sada paloker nirjonota.jpg",
    buyLink: "https://www.rokomari.com/book/207463/sada-paloker-nirjonota",
  },
];

export default books;
